// Mocks generated by Mockito 5.4.4 from annotations
// in vext/test/unit/attendance_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:vext/core/proto/mesh_packet.dart' as _i4;
import 'package:vext/services/firebase_sync_engine.dart' as _i5;
import 'package:vext/services/mesh_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MeshService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMeshService extends _i1.Mock implements _i2.MeshService {
  @override
  _i3.Stream<_i4.MeshPacket> get attendancePackets => (super.noSuchMethod(
        Invocation.getter(#attendancePackets),
        returnValue: _i3.Stream<_i4.MeshPacket>.empty(),
        returnValueForMissingStub: _i3.Stream<_i4.MeshPacket>.empty(),
      ) as _i3.Stream<_i4.MeshPacket>);

  @override
  _i3.Stream<_i4.MeshPacket> get messagePackets => (super.noSuchMethod(
        Invocation.getter(#messagePackets),
        returnValue: _i3.Stream<_i4.MeshPacket>.empty(),
        returnValueForMissingStub: _i3.Stream<_i4.MeshPacket>.empty(),
      ) as _i3.Stream<_i4.MeshPacket>);

  @override
  _i3.Stream<_i4.MeshPacket> get sosPackets => (super.noSuchMethod(
        Invocation.getter(#sosPackets),
        returnValue: _i3.Stream<_i4.MeshPacket>.empty(),
        returnValueForMissingStub: _i3.Stream<_i4.MeshPacket>.empty(),
      ) as _i3.Stream<_i4.MeshPacket>);

  @override
  _i3.Stream<_i4.MeshPacket> get ackPackets => (super.noSuchMethod(
        Invocation.getter(#ackPackets),
        returnValue: _i3.Stream<_i4.MeshPacket>.empty(),
        returnValueForMissingStub: _i3.Stream<_i4.MeshPacket>.empty(),
      ) as _i3.Stream<_i4.MeshPacket>);

  @override
  _i3.Stream<_i2.AttendanceAdvertisement> get attendanceAdvertisements =>
      (super.noSuchMethod(
        Invocation.getter(#attendanceAdvertisements),
        returnValue: _i3.Stream<_i2.AttendanceAdvertisement>.empty(),
        returnValueForMissingStub:
            _i3.Stream<_i2.AttendanceAdvertisement>.empty(),
      ) as _i3.Stream<_i2.AttendanceAdvertisement>);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> sendPacket(_i4.MeshPacket? packet) => (super.noSuchMethod(
        Invocation.method(
          #sendPacket,
          [packet],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [FirebaseSyncEngine].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseSyncEngine extends _i1.Mock
    implements _i5.FirebaseSyncEngine {
  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> syncNow() => (super.noSuchMethod(
        Invocation.method(
          #syncNow,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
